/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AprendaRouteImport } from './routes/aprenda'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoDeNftsRouteImport } from './routes/carrinho-de-nfts'
import { Route as CarteirasRouteImport } from './routes/carteiras'
import { Route as CriadoresRouteImport } from './routes/criadores'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MercadoRouteImport } from './routes/mercado'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as PerfilDoColecionadorRouteImport } from './routes/perfil-do-colecionador'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendaRoute = AprendaRouteImport.update({
  id: '/aprenda',
  path: '/aprenda',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoDeNftsRoute = CarrinhoDeNftsRouteImport.update({
  id: '/carrinho-de-nfts',
  path: '/carrinho-de-nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteirasRoute = CarteirasRouteImport.update({
  id: '/carteiras',
  path: '/carteiras',
  getParentRoute: () => rootRouteImport,
} as any)
const CriadoresRoute = CriadoresRouteImport.update({
  id: '/criadores',
  path: '/criadores',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MercadoRoute = MercadoRouteImport.update({
  id: '/mercado',
  path: '/mercado',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilDoColecionadorRoute = PerfilDoColecionadorRouteImport.update({
  id: '/perfil-do-colecionador',
  path: '/perfil-do-colecionador',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho-de-nfts': typeof CarrinhoDeNftsRoute
  '/carteiras': typeof CarteirasRoute
  '/criadores': typeof CriadoresRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil-do-colecionador': typeof PerfilDoColecionadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho-de-nfts': typeof CarrinhoDeNftsRoute
  '/carteiras': typeof CarteirasRoute
  '/criadores': typeof CriadoresRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil-do-colecionador': typeof PerfilDoColecionadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprenda': typeof AprendaRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho-de-nfts': typeof CarrinhoDeNftsRoute
  '/carteiras': typeof CarteirasRoute
  '/criadores': typeof CriadoresRoute
  '/login': typeof LoginRoute
  '/mercado': typeof MercadoRoute
  '/pagamento': typeof PagamentoRoute
  '/perfil-do-colecionador': typeof PerfilDoColecionadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/carrinho-de-nfts'
    | '/carteiras'
    | '/criadores'
    | '/login'
    | '/mercado'
    | '/pagamento'
    | '/perfil-do-colecionador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/carrinho-de-nfts'
    | '/carteiras'
    | '/criadores'
    | '/login'
    | '/mercado'
    | '/pagamento'
    | '/perfil-do-colecionador'
  id:
    | '__root__'
    | '/'
    | '/aprenda'
    | '/cadastro'
    | '/carrinho-de-nfts'
    | '/carteiras'
    | '/criadores'
    | '/login'
    | '/mercado'
    | '/pagamento'
    | '/perfil-do-colecionador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprendaRoute: typeof AprendaRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoDeNftsRoute: typeof CarrinhoDeNftsRoute
  CarteirasRoute: typeof CarteirasRoute
  CriadoresRoute: typeof CriadoresRoute
  LoginRoute: typeof LoginRoute
  MercadoRoute: typeof MercadoRoute
  PagamentoRoute: typeof PagamentoRoute
  PerfilDoColecionadorRoute: typeof PerfilDoColecionadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprenda': {
      id: '/aprenda'
      path: '/aprenda'
      fullPath: '/aprenda'
      preLoaderRoute: typeof AprendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho-de-nfts': {
      id: '/carrinho-de-nfts'
      path: '/carrinho-de-nfts'
      fullPath: '/carrinho-de-nfts'
      preLoaderRoute: typeof CarrinhoDeNftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteiras': {
      id: '/carteiras'
      path: '/carteiras'
      fullPath: '/carteiras'
      preLoaderRoute: typeof CarteirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criadores': {
      id: '/criadores'
      path: '/criadores'
      fullPath: '/criadores'
      preLoaderRoute: typeof CriadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mercado': {
      id: '/mercado'
      path: '/mercado'
      fullPath: '/mercado'
      preLoaderRoute: typeof MercadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil-do-colecionador': {
      id: '/perfil-do-colecionador'
      path: '/perfil-do-colecionador'
      fullPath: '/perfil-do-colecionador'
      preLoaderRoute: typeof PerfilDoColecionadorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprendaRoute: AprendaRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoDeNftsRoute: CarrinhoDeNftsRoute,
  CarteirasRoute: CarteirasRoute,
  CriadoresRoute: CriadoresRoute,
  LoginRoute: LoginRoute,
  MercadoRoute: MercadoRoute,
  PagamentoRoute: PagamentoRoute,
  PerfilDoColecionadorRoute: PerfilDoColecionadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
