/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrinhoDeNftsRouteImport } from './routes/carrinho-de-nfts'
import { Route as NftDetailsRouteImport } from './routes/nft-details'
import { Route as PagamentoRouteImport } from './routes/pagamento'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoDeNftsRoute = CarrinhoDeNftsRouteImport.update({
  id: '/carrinho-de-nfts',
  path: '/carrinho-de-nfts',
  getParentRoute: () => rootRouteImport,
} as any)
const NftDetailsRoute = NftDetailsRouteImport.update({
  id: '/nft-details',
  path: '/nft-details',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho-de-nfts': typeof CarrinhoDeNftsRoute
  '/nft-details': typeof NftDetailsRoute
  '/pagamento': typeof PagamentoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho-de-nfts': typeof CarrinhoDeNftsRoute
  '/nft-details': typeof NftDetailsRoute
  '/pagamento': typeof PagamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho-de-nfts': typeof CarrinhoDeNftsRoute
  '/nft-details': typeof NftDetailsRoute
  '/pagamento': typeof PagamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carrinho-de-nfts' | '/nft-details' | '/pagamento'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carrinho-de-nfts' | '/nft-details' | '/pagamento'
  id: '__root__' | '/' | '/carrinho-de-nfts' | '/nft-details' | '/pagamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoDeNftsRoute: typeof CarrinhoDeNftsRoute
  NftDetailsRoute: typeof NftDetailsRoute
  PagamentoRoute: typeof PagamentoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho-de-nfts': {
      id: '/carrinho-de-nfts'
      path: '/carrinho-de-nfts'
      fullPath: '/carrinho-de-nfts'
      preLoaderRoute: typeof CarrinhoDeNftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft-details': {
      id: '/nft-details'
      path: '/nft-details'
      fullPath: '/nft-details'
      preLoaderRoute: typeof NftDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoDeNftsRoute: CarrinhoDeNftsRoute,
  NftDetailsRoute: NftDetailsRoute,
  PagamentoRoute: PagamentoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
